### ISSUE TITLE
Hand-write the parser

### ISSUE THREAD

**Issue by anqurvanillapy** [rowscript/rowscript#97]

**Comment by anqurvanillapy** [comment]
Hand-written parser could eliminate the translation phace, the surface syntax would be the program tree for parsing, and the error messages could be now more informative too.

**Comment by anqurvanillapy** [comment]
Pratt parsing might be kinda hard to write in hand, let me see some.

**Comment by anqurvanillapy** [comment]
Considering using [winnow].

[winnow]: https://docs.rs/winnow/latest/winnow/

**Comment by SchrodingerZhu** [comment]
Or https://crates.io/crates/chumsky since you are already on its stack

**Comment by anqurvanillapy** [comment]
> https://crates.io/crates/chumsky

That's definitely a go, wow.

**Comment by anqurvanillapy** [comment]
For now it’s kinda challenging to change the front end, and it’s quite hard for me to clarify the this decision again. I guess I need to improve the error messages upon parsing first, and then possibly re-open related discussions with respect to changing the front end.
